keycloak:
  auth-server-url: <url_your_server>
  bearer-only: true
  credentials:
    secret: <client_secret_your_keycloak>
  principal-attribute: "preferred_username"
  realm: <your-realm>
  resource: <your-resource ou client>
  ssl-required: "none"
  use-resource-role-mappings: true

#  user you log in without keycloak admin
user-admin: <your-user-login-admin>
password-admin: <your-password-admin>

server:
  port: 8081
