keycloak:
  auth-server-url: ${KEYCLOAK_URL}/auth/
  bearer-only: true
  credentials:
    secret: ${KEYCLOAK_SECRET}
  principal-attribute: "preferred_username"
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  ssl-required: "none"
  use-resource-role-mappings: true

#  user you log in without keycloak admin
user-admin: ${KEYCLOAK_USER}
password-admin: ${KEYCLOAK_PASSWORD}

server:
  port: 8081
